name: Build & Push to container registry
on:
  workflow_call:
    inputs:
      TARGET_FILE:
        description: "Dockerfile to build"
        type: string
        required: false
        default: "Dockerfile"
      TARGET_IMAGE_NAME:
        description: "Docker image name"
        type: string
        required: false
        default: ""
      PLATFORMS:
        description: "Docker image platforms"
        type: string
        required: false
        default: "linux/amd64,linux/arm64/v8"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2.10.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: tags
        if: ${{ github.event_name == 'release' }}
        run: echo ::set-output name=name::${GITHUB_REF##*/}

      - name: Extract flavor
        id: flavor
        run: if [ "${{ github.event_name }}" = "release" ]; then echo ::set-output name=name::; else echo ::set-output name=name::-dev; fi
      
      - id: string
        uses: ASzc/change-string-case-action@d0603cd0a7dd490be678164909f65c7737470a7f # v6
        with:
          string: ${{ github.repository }}

      - name: Generate Docker image metadata
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4.6.0
        id: img_meta
        with:
          flavor: |
            latest=auto
          images: "ghcr.io/${{ inputs.TARGET_IMAGE_NAME || steps.string.outputs.lowercase }}"
          tags: |
            type=ref,event=branch
            type=sha,prefix=,suffix=,format=short

    
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@15560696de535e4014efeff63c48f16952e52dd1 # v6.2.0
        with:
          file: ${{ inputs.TARGET_FILE }}
          context: ./
          platforms: ${{ inputs.PLATFORMS }}
          tags: ${{ steps.img_meta.outputs.tags }}
          labels: ${{ steps.img_meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
          secrets: |
            GITHUB_SHA=${{ github.sha }}
            GH_PKG_TOKEN=${{ secrets.GH_TOKEN }}
          
